# Generated by Django 4.0.4 on 2022-05-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
